### ISSUE TITLE
Sorteos Lanzamiento GitTogether Santiago | AIEP | Miércoles, 10 de Abril

### ISSUE THREAD

**Issue by AndreaGriffiths11** [gittogethers/santiago#4]
## Evento en AIEP | Miércoles, 10 de Abril

¡Bienvenidos al primer evento presencial de la comunidad de [GitHub Santiago](https://www.meetup.com/gittogether-santiago/)! 🎉

Estamos increíblemente emocionados de recibirlos en este encuentro único y especial. Después de tiempo conectándonos virtualmente, por fin ha llegado el momento de reunirnos cara a cara y celebrar nuestra pasión por la tecnología y el desarrollo de software.

Queremos expresar nuestro más sincero agradecimiento a Gabriela Peñaloza y María Loreto Bustamante de AIEP, quienes han sido fundamentales en el apoyo y la organización de esta iniciativa.

Y, por supuesto, extendemos nuestra gratitud a todos ustedes, nuestra increíble comunidad. Su pasión, entusiasmo y compromiso son el motor que impulsa nuestro crecimiento y nos inspira a seguir adelante. 

<p align="center">
  <img width="520" alt="GitTogether Santiago" src="https://github.com/gittogethers/nerdearla-chile/assets/20666190/c4ca6072-a35a-432b-ba00-444fd4ad3121">
</p>

## Sorteos 

🎫 Para entrar en el sorteo, inicia sesión en tu cuenta de GitHub, ¿no tienes una? No hay problema, abre una gratis y agrega un comentario al final de este issue 👇, no habrás un issue nuevo, solo deja tu comentario.

🏆 Los premios se sortearán durante el evento.

✍🏽 Un par de Términos y Condiciones:

Participar en esta rifa NO constituirá tu consentimiento para ser contactado por cualquier otra cosa.
No te agregaremos a nuestra base de datos de marketing (pero si quieres suscribirte a nuestro boletín, puedes hacerlo [aquí](https://resources.github.com/newsletter/).

El premio de la rifa no se puede cambiar o intercambiar.
¡El ganador del premio DEBE estar presente cuando saquemos un ganador, de lo contrario, volveremos a sortear!
¡Buena suerte!

**Comment by oliverfierro77** [comment]
hi

**Comment by Caritopium** [comment]
Holaa buenas 😁

**Comment by Instacris** [comment]
Saludos desde aipe github

**Comment by Nachitorey** [comment]
Holii estamos activo

**Comment by bachsmann** [comment]
Hola!

**Comment by samhernand** [comment]
Saludos

**Comment by haitianmachine** [comment]
Increible

**Comment by Victoriguez** [comment]
Hola

**Comment by nedilio** [comment]
Hola GitHub!

**Comment by danieldevelop** [comment]
Hi, Saludos desde la Sede Aiep Maipú

**Comment by Instacris** [comment]
Saludos desde aiep bellavista

**Comment by Caritopium** [comment]
La ola 🌊🌊🌊🌊

**Comment by odracirdev** [comment]
¡Hola mundo!

**Comment by krlz-dev** [comment]
Hola

**Comment by Isaac4512** [comment]
Saludos

**Comment by lexO-dat** [comment]
Holaaaa :D

**Comment by sergioazoc** [comment]
Holis! Tremendo evento, vamos por más 🚀

**Comment by i-samedi** [comment]
Holaaaa!!! Encantado de estar en la primera charla de GitHub Chile, y ojalá no sea la última!

**Comment by Fabianko** [comment]
Holaaaa ✨️✨️✨️
Jschile.org presente 💚💛💚💛💚

**Comment by lahnie** [comment]
Holi!! 🩷🩷

**Comment by Edmundo-Ogaz** [comment]
Hi

**Comment by HugoosZ** [comment]
Holaa!👀

**Comment by krlz-dev** [comment]
Hola

**Comment by dbahamondes** [comment]
Quiero ganar un premio 🫡

**Comment by Caritopium** [comment]
😁❤️

**Comment by Astrid2312** [comment]
✌️✌️

**Comment by robinnn20** [comment]
Hola! 😌

**Comment by diegoaguilef** [comment]
El sorteoooo 😄😄😄

**Comment by Caritopium** [comment]
Premios para todos!! 😆

**Comment by Joberto14** [comment]
Holaaaa

**Comment by Pipeemendez** [comment]
Holaa

**Comment by VictorBetancourt** [comment]
Hi Octo Cat

**Comment by Caritopium** [comment]
🐈‍⬛

**Comment by fase99** [comment]
Buenas

**Comment by Suroniki** [comment]
Wenas

**Comment by JLCordova11** [comment]
Hola!!

**Comment by pablo1976github** [comment]
Presente... 🤟

**Comment by AlvaroMendezT** [comment]
Buenos dias :)

**Comment by elmalba** [comment]
Hola, en la devops conf no gane espero hoy ganar

**Comment by javis920320** [comment]
presente

**Comment by EstefaniaOlivares** [comment]
Presente ✨

**Comment by Luisjaquezuniga** [comment]
Hola a todos

**Comment by ale13-1** [comment]
Gracias por las charlas!

**Comment by Caritopium** [comment]
Presente 🐈‍⬛

**Comment by Benutd** [comment]
<h1> Hello Friend.

**Comment by armikhael** [comment]
Holaaa!!!

**Comment by KrlitosForever** [comment]
# Hola a todos 👋!
Un gusto haber compartido con todos Uds. Este evento. Agradecer la participación de @AndreaGriffiths11, @javs-perez, @juanpflores y a los campus expert @IgnacioPalma y @BGMP hacen un maravilloso trabajo. Son personas que inspiran a realizar un mejor trabajo.
Espero pronto los organizadores creen una organización dentro de github para tener proyectos en común. Con gusto puedo crear la organización para que sea un espacio de encuentro.
Quedo a disposición y les mando saludos desde #Copiapó 👋

**Comment by IgnacioPalma** [comment]
Que bueno que te gustó @KrlitosForever ! ❤️

Espero que nos podamos volver a ver. Saludos de Copiapino a Copiapino 🏜️

**Comment by AndreaGriffiths11** [comment]
@KrlitosForever 
He recibido una invitación para colaborar con su grupo. Con el fin de evitar confusiones y garantizar el uso de los recursos oficiales, quisiera pedirles amablemente que consideren cambiar el nombre de su organización.
Nos complace informarles que todas las gestiones y comunicaciones del grupo oficial se llevarán a cabo a través de este repositorio. Esto nos permitirá mantener un registro claro y centralizado de nuestras actividades y decisiones. https://github.com/gittogethers/santiago
Agradecemos de antemano su comprensión y colaboración en este asunto. Si tienen alguna pregunta o inquietud, no duden en comunicarse con nosotros.

**Comment by KrlitosForever** [comment]
> @KrlitosForever He recibido una invitación para colaborar con su grupo. Con el fin de evitar confusiones y garantizar el uso de los recursos oficiales, quisiera pedirles amablemente que consideren cambiar el nombre de su organización. Nos complace informarles que todas las gestiones y comunicaciones del grupo oficial se llevarán a cabo a través de este repositorio. Esto nos permitirá mantener un registro claro y centralizado de nuestras actividades y decisiones. https://github.com/gittogethers/santiago Agradecemos de antemano su comprensión y colaboración en este asunto. Si tienen alguna pregunta o inquietud, no duden en comunicarse con nosotros.

Si no te preocupes, elimino el grupo jajaja exceso de iniciativa, Saludos 👋

**Comment by KrlitosForever** [comment]
> Gracias por el apoyito! Combinemos fuerzas en ese repo :) ya en dos semanitas lanzamos el programa oficialmente pero mientras puedes comunicarte con Oli or Diego si quieres apoyar el grupo

Ya elimine la organización 👍🏻. Si mantuve contacto inicial con ellos, de momento no he vuelto a saber nada, en verdad no sé si existe algún plan de acción o si tienen alguna meta o planes a llevar a cabo para "Santiago".

**Comment by oliverfierro77** [comment]
Hola a todos
Las formas de colaborar estan descritas en el home de nuestro repo de la comunidad:
https://github.com/gittogethers/santiago

Atentos a los eventos y convocatorias durante el año!
Los esperamos como speakers durante el año.

Si quieren proponer algo puntual que no este descrito, nos pueden hablar directamente a nuestros correos de contacto.
