### ISSUE TITLE
Error link whatsapp

### ISSUE THREAD

**Issue by KrlitosForever** [gittogethers/santiago#5]
Al revisar el link de whatsapp genera el siguiente error ⬇️ [README](https://github.com/gittogethers/santiago/blob/main/README.md)

![image](https://github.com/gittogethers/santiago/assets/7423579/0ed0328f-8d19-4b5a-b19a-6e75ec0ed05a)

Olvidaron agregar el link?⬇️ 
![image](https://github.com/gittogethers/santiago/assets/7423579/baee649b-13f9-4862-86ca-5db8f513fda8)

**Comment by oliverfierro77** [comment]
done

**Comment by oliverfierro77** [comment]
done
